### ISSUE TITLE
Full screen mode causes a black background under chrome

### ISSUE THREAD

**Issue by DavidPowell** [damianavila/RISE#158]
Going into fullscreen mode in google chrome results in a black background, which makes black text rather difficult to read. This is due to an issue in reveal.js (hakimel/reveal.js/#1386), which has been fixed in master. However, upgrading the version of reveal.js shipped with RISE causes many other formatting problems.

My current workaround is to use firefox. In both cases, I am working under windows.

**Comment by damianavila** [comment]
Thanks for the report, I have some branch updating reveal... this should be fixed soon.

**Comment by quebbs** [comment]
This only appears to happen when pressing 'F' to go full screen; using F11 still appears to work fine in Chrome.

**Comment by damianavila** [comment]
Probably related with keyboard shortcut conflict.

**Comment by damianavila** [comment]
This one is addressed in https://github.com/damianavila/RISE/pull/256
