### ISSUE TITLE
trouble installing RISE // no button visible

### ISSUE THREAD

**Issue by paulelvers** [damianavila/RISE#520]
I am installing RISE in a python 3.6 virtualenv with pip  and the following dependencies:

jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
nbconvert==5.6.1
nbformat==4.4.0
notebook==6.0.2
rise==5.5.1

I am NOT running  `jupyter-nbextension install rise --py --sys-prefix`as recommended. 

However, after installation and running jupyter in the shell, there is no RISE button next to the keyboard and hotkeys won't work either.

Is this a compatibility issue? I tried downgrading juptyer, notebook and rise but it didn't solve the issue.

**Comment by parmentelat** [comment]
Hey

Many users have reported that issue, which to the best of my knowledge is fixed in the devel version of rise, known as 5.6, (which is good to use but was not released due to lack of availability by the original author)

Please try out that dev release with `pip install -U rise --pre`  
(indeed the other options do not matter, it's up to you entirely to use --sys-prefix or not)

**Comment by parmentelat** [comment]
I'd appreciate if you could confirm whether this has solved your issue or not

**Comment by paulelvers** [comment]
Hi, thank you for the suggestions but this did not resolve the issue. I installed the dev version 5.6 but it still does not work. I do niether see the button, nor am able to use the hotkeys.

**Comment by paulelvers** [comment]
Do you know any other way to solve this or can you give more information on the causes of this issue?

**Comment by parmentelat** [comment]
Can you post a screenshot or your browser console ?

**Comment by damianavila** [comment]
Additionally, it would be nice to know if you have other extension installed (and if that is the case, which ones?). Can we also get a list of the dependencies on that environment?
Are you seeing the same with previous versions of RISE?

**Comment by ziqing-ang** [comment]
Hi @parmentelat  @damianavila , 
I'm encountering presumably similar issues when installing RISE. I've actually intended to try jupyterlab_rise in the first place but there was some npm issue so I was going to try RISE on the notebook instead.  I've installed rise by 
`python3 -m pip install --user RISE`
and I have run these 
`jupyter-nbextension install rise --py --user`
`jupyter-nbextension enable rise --py --user`
but since the docs said it was unnecessary,
 [https://rise.readthedocs.io/en/maint-5.6/installation.html](url)
 I thought maybe it's not the issue of enabling it in the extension?
My dependencies are:
jupyter core     : 4.6.0
jupyter-notebook : 6.0.1
qtconsole        : not installed
ipython          : 7.8.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.1.4
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3
rise                     5.6.0

**Comment by parmentelat** [comment]
Can you please try to describe your symptoms more accurately ?
What were you expecting to see and what are you seeing instead ?
Can you post a screenshot ?

**Comment by ziqing-ang** [comment]
Hi @parmentelat 
I have been able to get RISE running after installing conda and then rise.
I've been reluctant on getting conda for a long time and has been relying on pip, so I was expecting RISE to work after installing via pip, which didn't happen. So right now RISE works when I do
`conda activate`
before running the notebook, i.e. I now have conda solely for the sake of having RISE running lol. 
I understand the extension of rise to jupyterlab is a work-in-progress, so I'm okay having to use RISE in the notebook atm. I'm not sure what happened to the RISE I've installed via pip, it seems like there is a disconnection to jupyter notebook, so I ran
`~ $ jupyter nbextension install rise --py --user
Traceback (most recent call last):
  File "/home/ziqingang/.local/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/home/ziqingang/.local/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/ziqingang/.local/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/home/ziqingang/.local/lib/python3.7/site-packages/jupyter_core/application.py", line 257, in start
    self.subapp.start()
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/ziqingang/.local/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/home/ziqingang/.local/lib/python3.7/site-packages/rise/__init__.py", line 3, in <module>
    __version__ = pkg_resources.require("rise")[0].version
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.10.0 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.11.0'), {'jsonschema'})
`
Is still enough to see what is wrong?

**Comment by ziqing-ang** [comment]
I came across this reply and gave it a try
[https://github.com/damianavila/RISE/issues/428#issuecomment-440736983](url)
when I ran 
`sudo python3 setup.py install`
I got this message at the end of the log
`Installed /usr/local/lib/python3.7/dist-packages/rise-5.6.0.dev3-py3.7.egg
Processing dependencies for rise==5.6.0.dev3
error: six 1.10.0 is installed but six>=1.11.0 is required by {'jsonschema'}`
so I tried updating six and ran the same line again. Then I got this
`Using /home/ziqingang/.local/lib/python3.7/site-packages
Finished processing dependencies for rise==5.6.0.dev3`
so I assume it has done its work.

Then I run the next line
`sudo jupyter-nbextension install rise --py --sys-prefix`
and at the end of the log I've got this
`- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable rise --py --sys-prefix`
and again I assume things went well. But when I ran the last line
`jupyter nbextension enable rise --py --sys-prefix`
I got this log:
Traceback (most recent call last):
  File "/home/ziqingang/.local/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/home/ziqingang/.local/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/ziqingang/.local/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/home/ziqingang/.local/lib/python3.7/site-packages/jupyter_core/application.py", line 257, in start
    self.subapp.start()
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/ziqingang/.local/lib/python3.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/ziqingang/.local/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/usr/local/lib/python3.7/dist-packages/rise-5.6.0.dev3-py3.7.egg/rise/__init__.py", line 3, in <module>
    __version__ = pkg_resources.require("rise")[0].version
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.10.0 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.11.0'), {'jsonschema'})

**Comment by ziqing-ang** [comment]
oh wait I forgot my `sudo`

**Comment by ziqing-ang** [comment]
jupyter in my system had some problem (some syntax error message) after I did this. I wasn't sure what happened in between but in the end
`sudo easy_install3 pip`
solved the problem. Rise is now working in my notebook now, I've gotten rid of Miniconda. Thanks.

**Comment by PrometheusPi** [comment]
@parmentelat I get the same issues as @paulelvers - I used a fresh conda  environment and installed rise via `conda install -c conda-forge rise`. A `rise` module is available, but the typical drop down menu above each cell is missing.  

![grafik](https://user-images.githubusercontent.com/5121158/70327148-7779e800-1836-11ea-8484-5b45c84ed1a1.png)

As you can see from the screen-shot, rise is available but the interface is missing. 

I am using:
```
python 3.6.9 :: Anaconda, Inc.
```

Any idea what might causes this issue and how to resolve it?

**Comment by parmentelat** [comment]
@PrometheusPi 

just to be clear, the drop-down above each cell is a feature that is independant of RISE; 
it is something that you need to enable separately - see below - and for that you do not need to have RISE installed

![image](https://user-images.githubusercontent.com/4519227/70330749-777de600-183e-11ea-86cc-3985d5a32141.png)

is there any other symptom that make you think that rise is not available ? 
like, can you start a slide show by typing 'Alt-r' ? 

a screenshot of your javascript console may shed some light as well

**Comment by PrometheusPi** [comment]
Okay - thanks - the `Slideshow` option is available and I can activate it (sorry - my last time running RISE is about a year ago with version `0.5.3`).

However, neither `Alt + r` starts the slide show, nor is there a RISE button as in previous versions 
![grafik](https://user-images.githubusercontent.com/5121158/70332064-0ab81b00-1841-11ea-8d04-cdb721f0c3fd.png)
(right most button in the picture).

 I am using firefox `71.0` on MacOS `10.14.6`. 
I just tested it with the same firefox on the old `0.5.3` RISE, it it works. In `0.5.6` however, it does not show up. 
The "new" env is on a remote jupyter lab (but I am using the classic `/tree` interface to avoid the lab incompatibility with jupyter labs and RISE). 

How do I access the javascript console and what do you need? 

I will test the current RISE locally and check whether the issue arises as well, perhaps it is just the remote jupyter lab that blocks part of the interface.

**Comment by parmentelat** [comment]
the javascript console is part of the developer tools in the browser; on chrome for example I can activate it using either the *View* -> *Developer* -> *Javascript Console*  menu; or I can type `Command-Option I` and then select the 'Console' Tab to get all the messages issued by the javascript runtime. Ask google for any other environment you would be using instead. 

Please post a screenshot corresponding to the notebook loading time period, ideally focusing on what looks fishy or suspicious, if that makes sense to you.

**Comment by parmentelat** [comment]
as an afterthought
we've seen this issue reported by quite a few people; I thought I had fixed it in 5.6.0 but your report proves otherwise
regardless, the issues I had found were related to using rise together with other extensions; so out of curiosity could you list the extensions that are enabled within this jupyter session ? if that's something you have access to of course

**Comment by PrometheusPi** [comment]
Okay - I will try. 

The local installation of RISE showed the button (and it worked) - but `Alt + r` failed again. 

Thus it is definite (partially) an issue with the jupyter hub (`/tree`) interface.

**Comment by parmentelat** [comment]
so, that's better already I guess :)

the fact that alt-r won't work is puzzling; the jupyter interface has a Help menu with two entries that show keyboard shortcuts; do you see the 'slideshow' function attached to 'alt-r' in there ?

FYI in my 'Edit Keyboard Shortcuts' view I can see this extract

![image](https://user-images.githubusercontent.com/4519227/70334430-b6636a00-1845-11ea-9d48-55a0c55a182d.png)

**Comment by PrometheusPi** [comment]
locally (where the button appears) - I have no extensions in jupyter but a *Adblock Plus* Add-on in Firefox.

remotely: as far es I can tell extensions seems to be disabled 

In bath cases the console shows ma a blockt java script:
(please excuse, my setup is German):
```
Die Ressource von "http://localhost:8888/nbextensions/widgets/notebook/js/extension.js?v=20191206161539" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
```
leading to the following error https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

**Comment by PrometheusPi** [comment]
Furthermore there are some loading warnings in the remote version. But one looks interesting to me:

```
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: https://<servername>.de/jupyter/user/<usernam>/stat…c/notebook/js/main.min.js?v=1bc4ae6ca8730320ff059b16de698691
Source-Map-Adresse: main.min.js.map
```
(I removes some of the user specific data.)

**Comment by PrometheusPi** [comment]
In my local setup, the commands are available:
![grafik](https://user-images.githubusercontent.com/5121158/70335713-1fe47800-1848-11ea-8d9a-207b019a3884.png)

It seems to work (most likely a mistyped the command before.)

On the remote machine, there are no RISE key commands in the list.

**Comment by PrometheusPi** [comment]
Even if I use a self-installed anaconda (and not the jupyter hub provided by the facility) on that remote machine (and start via `jupyter notebook`, I can not access the RISE commands nor is there a button to start the slideshow.

**Comment by PrometheusPi** [comment]
If I inspect the firefox debugger - the local (working) version shows a source called `nbextensions/rise`
![grafik](https://user-images.githubusercontent.com/5121158/70337060-a39f6400-184a-11ea-875f-10601a50071c.png)

while my self-installed non-working remote versions seems to have only a widget-extension `nbextensions/jupyter-js-widgets`
![grafik](https://user-images.githubusercontent.com/5121158/70337158-d21d3f00-184a-11ea-8c2d-a20c0b52da52.png)

This might cause the issue - I will try to setup a (hopefully) clean environment without widgets.

**Comment by PrometheusPi** [comment]
Update: 
a clean python 3.6 environment with rise works fine (even on the remote machine). 

I will now additionally install widgets and test whether it then fails.

**Comment by PrometheusPi** [comment]
@parmentelat Sorry for not replying back - I was busy with other things after I had a working version. I will ask the IT as soon as possible - but this might be delayed until after New Year due to the upcomming holidays.

**Comment by PrometheusPi** [comment]
@parmentelat the IT department replied back today after a month - they will start investigating the issue.

**Comment by damianavila** [comment]
Interesting stuff, let us know any feedback you may get from them.

**Comment by PrometheusPi** [comment]
@damianavila They replied again but did not provide feedback what caused the issue. They set it up as default extension now on the cluster's jupyter hub. That solved the issue from my side. 
I am sorry I could not provide more details.

**Comment by albert-kevin** [comment]
here it works:
https://40.68.149.232:8000/user/ubuntu/notebooks/azuremachinelearning/python/test1.ipynb

here it does not:
https://52.174.93.138:8000/user/ubuntu/notebooks/azuremachinelearning/python/test1.ipynb

user = ubuntu
passw = ABCD1234abcd

I leave these servers open for 24h...
I can't figure out why ?

**Comment by parmentelat** [comment]
> On 4 Mar 2020, at 14:02, Kevin ALBERT <notifications@github.com> wrote:
> 
> here it works:
> https://40.68.149.232:8000/user/ubuntu/notebooks/azuremachinelearning/python/test1.ipynb
> 
> here it does not:
> https://52.174.93.138:8000/user/ubuntu/notebooks/azuremachinelearning/python/test1.ipynb
> 
> user = ubuntu
> passw = ABCD1234abcd
> 
> I leave these servers open for 24h...
> I can't figure out why ?

well at first sight obviously rise-5.3.0 is not going to work as of 2020

there seems to be something really fishy about these depls though; 
at some point I did see some reference to 5.6.1 in there but that apparently vanished after I ran pip install rise again

in any case, you first want to make sure that you use 5.6 at the very least

**Comment by albert-kevin** [comment]
I happen to have time today...
creating new server with RISE not yet installed
https://40.68.226.98:8000/user/ubuntu/notebooks/azuremachinelearning/python/test2.ipynb

**Comment by parmentelat** [comment]
hi
i gave that a quick try; unfortunately I could not find my way out after the 15 minutes i had allotted to myself :)

because the javascript console was complaining about 

> Failed to load extension: Array(1) Error: Script error for "nbextensions/nbextensions_configurator/config_menu/main"

I tried to install that (which I happen to have in my own docker images) but to no avail; on second thought that's not the right angle here

as far as I can tell though, this does not belong with rise as a matter of fact, because the rise extension does not even begin to try and load in this setup apparently
so if I were you, instead of adding stuff like I have just tried, I'd start on the contrary with fewer extensions - preferably none at all - and add only rise at first, which will work fine I'd tend to think, and then add the other ones to see if they break anything

**Comment by albert-kevin** [comment]
> hi
> i gave that a quick try; unfortunately I could not find my way out after the 15 minutes i had allotted to myself :)
> 
> because the javascript console was complaining about
> 
> > Failed to load extension: Array(1) Error: Script error for "nbextensions/nbextensions_configurator/config_menu/main"
> 
> I tried to install that (which I happen to have in my own docker images) but to no avail; on second thought that's not the right angle here
> 
> as far as I can tell though, this does not belong with rise as a matter of fact, because the rise extension does not even begin to try and load in this setup apparently
> so if I were you, instead of adding stuff like I have just tried, I'd start on the contrary with fewer extensions - preferably none at all - and add only rise at first, which will work fine I'd tend to think, and then add the other ones to see if they break anything

ok, I appreciated your support and time to look into this.
I am going to ignore this, got a workaround using notebooks.azure.com with RISE ready

**Comment by kurtmckee** [comment]
I recommend closing this ticket for lack of information.

Multiple posters with different setups have been asked for screenshots or lists of extensions and no responses have provided the requested information. In addition, each poster has left after stating that things are working or they found a workaround.

**Comment by PrometheusPi** [comment]
Sorry for not having a lot of time to investigate this further (from a user side). I agree with @kurtmckee, if inactive issues should be closed in the rise repo, please do so.

 @ parmentelat , @damianavila thanks for your support.

**Comment by Albert-26** [comment]
Hi,

I tried to work on some of the solutions provided, can someone help me with getting the presentation button in jupyter notebook, I have installed RISE using pip3 install RISE. But still not able to get the presentation button next to the command palette, are there anymore steps that I am missing?

**Comment by parmentelat** [comment]
hi
some common causes for that behaviour are
. mixing up between virtual environments (installing in one, running in another)
. some other extension fails to load and keeps rise from starting up

but we need a little more specific info to get a chance to help..
you can start with observing the web console to find some clue about your specific problem
feel free to post that over here if needed
